### ISSUE TITLE
[BUG] Some git commands are executed under destination directory's owner account

### ISSUE THREAD

**Issue by x-yuri** [npm/pacote#14]
# What / Why

> It might so happen that `root` installs packages into a directory owned by another user. Consider a case where you launch an app with `docker-compose` and bind mount the host directory with source code (`.`) into the container (`/app`) for changes to source code to automatically propagate into the container. Under this circumstances we get `root` user and `/app` owned by uid `1000`. During `fetch-package-metadata` phase it succeeds, since nothing says it has to impersonate:

https://github.com/npm/cli/blob/v6.12.1/lib/fetch-package-metadata.js#L59-L65
https://github.com/npm/pacote/blob/v9.5.8/manifest.js#L25
https://github.com/npm/pacote/blob/v9.5.8/lib/finalize-manifest.js#L49
https://github.com/npm/pacote/blob/v9.5.8/lib/finalize-manifest.js#L154
https://github.com/npm/pacote/blob/v9.5.8/lib/fetch.js#L33
https://github.com/npm/pacote/blob/v9.5.8/lib/fetchers/git.js#L71-L73
https://github.com/npm/pacote/blob/v9.5.8/lib/fetchers/git.js#L176

But when it comes to extracting the tarball, it fails owing to [`inferOwner()`][2] call.

[2]: https://github.com/npm/pacote/blob/v9.5.8/extract.js#L40

https://github.com/npm/cli/blob/v6.12.1/lib/install/action/extract.js#L90
https://github.com/npm/pacote/blob/v9.5.8/extract.js#L42
https://github.com/npm/pacote/blob/v9.5.8/lib/with-tarball-stream.js#L96
https://github.com/npm/pacote/blob/v9.5.8/lib/fetch.js#L28
https://github.com/npm/pacote/blob/v9.5.8/lib/fetchers/git.js#L44
https://github.com/npm/pacote/blob/v9.5.8/lib/fetchers/git.js#L71-L73
https://github.com/npm/pacote/blob/v9.5.8/lib/fetchers/git.js#L176

## When

* When I install packages from GitHub.

## Where

* n/a

### Current Behavior

* It ends with:

```
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/kevva/is-positive.git /root/.npm/_cacache/tmp/git-clone-d80b8730/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d80b8730/.git'
```

### Steps to Reproduce

Create files based on the following [gist][1] and do `docker-compose up`:

`docker-compose.yml`:

```yaml
version: '3'

services:
  app:
    build: .
    # entrypoint: sleep 10000000
    # ports:
      # - 9229:9229
    volumes:
      - ./:/app
```

`Dockerfile`:

```dockerfile
FROM node:12.13.0-alpine

RUN apk add git vim
WORKDIR /app

ENTRYPOINT ["./entrypoint.sh"]
```

`entrypoint.sh`:

```sh
#!/bin/sh
set -eu
npm i || true
cat /root/.npm/_logs/*.log
```

```
$ chmod u+x entrypoint.sh
$ docker-compose up
```

As you might guess the issue was discovered in a `docker` container. Alternatively, 

```
# useradd -m u1
# cd /home/u1
# echo '{"dependencies": {"is-positive": "kevva/is-positive"}}' > package.json
# npm i
```

[1]: https://gist.github.com/x-yuri/24e0f04acc6b7942e1ec860a554a949f

### Expected Behavior

* It either succeeds in both cases (`extract`, `fetch-package-metadata`), or fails. Preferably the former.

## Who

* n/a

## References

* Related to #2

**Comment by isaacs** [comment]
Fixed in 9.5.10 and 10.2.1.

9.5.10 will be included in the next npm v6 release.  10.2.1 (or some later v10) will be included in npm v7.

**Comment by x-yuri** [comment]
I've improved the description since it was pretty bad. And wanted to add that [the following commit][i476] doesn't solve the issue, because it's not that a non-root tries to switch users, but that root switches users when it shouldn't. The decision must depend on where the files are to be created. Which is handled by [the following commit][i624]. So supposedly this issue [doesn't affect][1] `pacote@10.x`.

It was fixed in [`npm-6.13.6`][fixed-npm], [`pacote-9.5.12`][fixed-pacote]. It was resolved in [`nodejs >= 13.7.0` (`npm >= 6.13.6`)][2], but not in `nodejs 10`, `nodejs 12` yet. But updating `npm` should resolve the issue where it exists by default.

[i476]: https://github.com/npm/pacote/commit/5f33040#diff-b00e824c75971ae2d4f13345124a8d54R244
[i624]: https://github.com/npm/pacote/commit/d2f4176b6af393d7e29de27e9b638dbcbab9a0c7#diff-b00e824c75971ae2d4f13345124a8d54R191
[1]: https://github.com/npm/cli/issues/624#issuecomment-569786396
[fixed-npm]: https://github.com/npm/cli/commit/6dba897a1
[fixed-pacote]: https://github.com/npm/pacote/commit/d2f4176b6af393d7e29de27e9b638dbcbab9a0c7#diff-b00e824c75971ae2d4f13345124a8d54R191
[2]: https://nodejs.org/en/download/releases/

**Comment by isaacs** [comment]
@x-yuri So, iiuc, it _is_ fixed, just not in the commit that we thought fixed it?

**Comment by x-yuri** [comment]
Yes, it is fixed in [`pacote@9.5.12`][1]. And judging from the [related issue][2], it's not an issue in `pacote@10.x`. Although I didn't try to confirm the latter.

[1]: https://github.com/npm/pacote/commit/d2f4176b6af393d7e29de27e9b638dbcbab9a0c7#diff-b00e824c75971ae2d4f13345124a8d54R191
[2]: https://github.com/npm/cli/issues/624#issuecomment-569786396
